import { it, expect } from 'vitest';
import { cloneOfficial, movePlayer } from './lineup';
import { encodeShare, decodeShare, saveDraft, loadDraft, loadInitial, storageKey, serializeDraft } from './serialization';
import { discordExport } from './discordExport';
import { composition } from './calculations';
const storage=()=>{const data=new Map<string,string>();return {getItem:(key:string)=>data.get(key)??null,setItem:(key:string,value:string)=>{data.set(key,value)},removeItem:(key:string)=>{data.delete(key)}}};
it('local storage round trip',()=>{const s=storage(),l=movePlayer(cloneOfficial(),'papij','reserves').lineup;saveDraft(s,l);expect(loadDraft(s).lineup).toEqual(l)});
it('malformed local storage fallback',()=>{const s=storage();s.setItem(storageKey,'{oops');expect(loadInitial('',s).mode).toBe('official');expect(loadInitial('',s).warning).toMatch(/saved/i)});
it('rejects unsupported storage schema',()=>{const s=storage();s.setItem(storageKey,JSON.stringify({v:999,...cloneOfficial()}));expect(loadDraft(s).lineup).toBeUndefined()});
it('rejects incomplete persisted assignments',()=>{const s=storage();s.setItem(storageKey,JSON.stringify({v:1,teams:[[],[],[],[]],reserves:[]}));expect(loadDraft(s).lineup).toBeUndefined()});
it('storage access denial cannot crash',()=>{const s={getItem:()=>{throw Error('denied')},setItem:()=>{throw Error('denied')},removeItem:()=>{throw Error('denied')}};expect(loadInitial('',s).mode).toBe('official');expect(saveDraft(s,cloneOfficial())).toBe(false)});
it('shared URL round trip',()=>{const l=movePlayer(cloneOfficial(),'papij','reserves').lineup;expect(decodeShare(encodeShare(l))).toEqual(l)});
it('serialization deterministic and no player database',()=>{const text=encodeShare(cloneOfficial());expect(encodeShare(cloneOfficial())).toBe(text);expect(JSON.parse(atob(text.slice(8).replace(/-/g,'+').replace(/_/g,'/')))).toEqual({v:1,teams:cloneOfficial().teams,reserves:cloneOfficial().reserves});expect(serializeDraft(cloneOfficial())).not.toMatch(/power|rank|class|status/)});
it('malformed URL falls back to saved draft with warning',()=>{const s=storage(),l=movePlayer(cloneOfficial(),'papij','reserves').lineup;saveDraft(s,l);const r=loadInitial('#lineup=bad',s);expect(r.lineup).toEqual(l);expect(r.warning).toMatch(/shared/i)});
it('oversized shared input rejects',()=>expect(decodeShare('#lineup='+ 'x'.repeat(10001))).toBeUndefined());
it('unknown IDs in hash reject',()=>{const l=cloneOfficial();l.teams[0][0]='ghost';expect(decodeShare(encodeShare(l))).toBeUndefined()});
it('shared URL takes precedence without reading persisted draft',()=>{const s=storage();saveDraft(s,movePlayer(cloneOfficial(),'papij','reserves').lineup);expect(loadInitial(encodeShare(cloneOfficial()),s).mode).toBe('shared');expect(loadInitial(encodeShare(cloneOfficial()),s).lineup).toEqual(cloneOfficial())});
it('Discord includes computed totals/classes',()=>{const d=discordExport(cloneOfficial());expect(d).toContain('Team 1 — 175.7M Total');expect(d).toContain('2 Templars / 2 Magisters');expect(d).toContain(':blue_circle: **PapiJ** — 51.2M — Magister')});
it('Discord reflects edited visible lineup',()=>{const d=discordExport(movePlayer(cloneOfficial(),'papij','reserves').lineup);expect(d).toContain('Team 1 — 124.5M Total');expect(d.slice(d.indexOf('Reserve Pool'))).toContain('**PapiJ**')});
it('inactive Discord suffix',()=>expect(discordExport(cloneOfficial())).toContain('**Morganna** — 29.8M — Templar — INACTIVE'));
it('composition singular and plural grammar for all classes',()=>{expect(composition(['mrbuttlips','ksha','papij','morgause'])).toBe('1 Templar / 1 Ravager / 1 Magister / 1 Prophet');expect(composition(['mrbuttlips','flowzirrah','ksha','marisze','papij','mookie','morgause','maciel'])).toBe('2 Templars / 2 Ravagers / 2 Magisters / 2 Prophets')});
